spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/CodaGonki}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres123}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:default-dev-secret}
  access-token-expiration: 900000      # 15 минут в миллисекундах
  refresh-token-expiration: 2592000000 # 30 дней в миллисекундах